update monitoring doc
privacysandbox/protected-auction-services-docs pull request #147
Opened 2024-08-02 14:34 UTC by xinggao01

2024-08-02 15:32 UTC, dmdabbs commented on monitoring_protected_audience_api_services.md
> +This proposal implements mechanisms to provide telemetry data using privacy-preserving technologies. Services running inside a TEE are now able to export common system and business metrics using thes
thatwill -> that will

2024-08-02 15:34 UTC, dmdabbs commented on monitoring_protected_audience_api_services.md
> +*   Other metrics do not have noise added, but are aggregated by OpenTelemetryfor performance reasons, before being published.
OpenTelemetryfor -> OpenTelemetry for

2024-08-02 15:39 UTC, dmdabbs commented on monitoring_protected_audience_api_services.md
> +An ad tech can choose to alter how the privacy budget is distributed across different metrics. See the
Missing reference...

>See the

2024-08-02 15:56 UTC, xinggao01 commented on monitoring_protected_audience_api_services.md
> +An ad tech can choose to alter how the privacy budget is distributed across different metrics. See the
Thanks.

2024-08-12 08:31 UTC, akshaypundle requested changes

2024-08-12 08:31 UTC, akshaypundle commented on monitoring_protected_audience_api_services.md
> +All Privacy Impacting metrics split total privacy budget based on their weight. i.e. privacy_budget = total_budget\*privacy_budget_weight /total_weight.
spaces around operators (/ and *)

2024-08-12 08:31 UTC, akshaypundle commented on monitoring_protected_audience_api_services.md
> +The probability that noisy values will be turned to 0. Setting this to a higher value ensures that the noisy values will be turned to 0, but also means that some actual (non-noisy values) may also be
i think we should say what noisy values means ... as written this one is a little unclear.

2024-08-13 17:30 UTC, akshaypundle approved these changes

2024-08-14 14:51 UTC, merged